[site]
title = "Xixian Huang"
description = "CS student at UOW, Risk Analyst Intern at Binance"
favicon = "/favicon.svg"
last_updated = "November 29, 2025"

[author]
name = "Xixian Huang"
title = "CS Student | Risk Analyst"
institution = "University of Wollongong | Binance"
avatar = "/avatar.gif"

[social]
# Contact information (leave blank or delete to hide)

email = "xixianhuang985@gmail.com"
location = "Australia"
location_url = "https://www.google.com/maps/place/Wollongong+NSW+2500/@-34.4282509,150.8724589,14z/data=!3m1!4b1!4m6!3m5!1s0x6b1319a51f0b567b:0x5017d681632e720!8m2!3d-34.4248336!4d150.8931132!16zL20vMDFqMTJ3?entry=ttu&g_ep=EgoyMDI1MTEyMy4xIKXMDSoASAFQAw%3D%3D"
location_details = [
  "Wollongong",
  "NSW"
]
github = "https://github.com/heyinwong"
linkedin = "https://linkedin.com"

[features]
# Show a like button on the about page
enable_likes = true

# Display all subpages on a single page
enable_one_page_mode = false

[[navigation]]
title = "About"
type = "page"
target = "about"
href = "/"


[[navigation]]
title = "Experience"
type = "page"
target = "experience"
href = "/experience"


[[navigation]]
title = "Projects"
type = "page"
target = "project"
href = "/project"

[[navigation]]
title = "Others"
type = "page"
target = "more"
href = "/more"

[[navigation]]
title = "CV"
type = "page"
target = "cv"
href = "/cv"
